name: Run Python Script Every 90 Minutes

on:
  schedule:
    # Runs every 60 minutes (UTC time)
    - cron: "0 */1 * * *"  # This runs at the top of every hour (adjust later for 90 mins)
  workflow_dispatch:  # This allows you to manually trigger the action if needed

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run authentication script
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: python main.py
