name: Run Python Script Every 90 Minutes

on:
  schedule:
    # Runs every 90 minutes (UTC time)
    - cron: "0 */1 * * *"  # This runs at the top of every hour (adjust later for 90 mins)
    # To run every 90 minutes, you'd need multiple cron expressions
    - cron: "30 */1 * * *"  # This runs 30 minutes after the hour to complete the 90-minute cycle
  workflow_dispatch:  # This allows you to manually trigger the action if needed

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Python script
        run: |
          python main.py
